### ISSUE TITLE
Matebook 13 after install 

### ISSUE THREAD

**Issue by Pedroooow** [Edoardo001/Matebook-13-Hackintosh#10]
Hi Edoardo :) 

1st, thanks for the good job making this possible. 

It's my 1st Hackintosh, so I don't know how I managed to install everything, but it works rather well. 

My hardware: 
- Matebook 13
- I5 8265u / 8gb / HD620
- had the Samsung 250gb SSD, swapped it for the Crucial P1 1TB
- Bought a TP link AC600 on Amazon, works well with  Wireless adapter Clover V14. 

Everything works fine, I managed to get it booting on its own without the usb drive (again, not a big step but 1st time Hackintosh user here :) ). 

However, there are 2 or 3 things that bugs me: 

Performance: 
I ran a Geekbench CPU perf, and I'm a bit disappointed in the results. I get SC: 794 / MC : 2590 which is close to what you would expect from a 5 years old MacBook Pro. I kinda hoped better perf. 

Fan noise: 
I've installed HWMonitor to monitor the CPU temps cause my Matebook barely goes to silent more. 
As soon as I start some task (can even be browsing safari) fans start and make a hell of a lot more noise than in windows. 
I guess this can be patched/improved by getting into some settings, but I'm still a newbie and don't really know where to start :) 

Regarding the temps, it's silent under 50°C and becomes noisy around 60°C, providing these temps are actually accurate. 

From what I remembered from my Desktop build, cpu is fine as long as it's under 70-85°C on a desktop. But is it the same on a laptop ? Or is it more sensitive as it's a rather closed case ? Any recommendation on the temps not to get over ? 

Anyway, I'd be happy if you had any tip/feedbacks on my post, and will keep on searching my way in the meantime ! 

Cheers :)

**Comment by Hirudyna** [comment]
right, I agree with you. well, except my bluetooth is tricky (in macOS it show that it's turned on and "working" but it cannot find any bluetooth devices. it's also not showing on other devices)

**Comment by Pedroooow** [comment]
@Hirudyna I had the same issue with Bluetooth. 
Solved it by copying IntelBluetoothFirmare.kext and IntelBluetoothInjector.kext from the CloverPost/CLOVER/kexts/Other onto SSD's EFI (Mount EFI with Clover configurator). Rebooted and all works fine :)

**Comment by Hirudyna** [comment]
Thank You for responding. I should’ve mentioned that I installed the Mojave version (and those kexts are in Catalina Folders). However i tried to follow your steps but still nothing has changed. Maybe i should try to update from Mojave to Catalina version someday and try it. Thank you anyway

**Comment by skynightz93** [comment]
The current solution is to use cpufriend. However, our cpu will not run at the optimal speed but still help to reduce fan noise

**Comment by Edoardo001** [comment]
I have no time because of my work but i plan for the future to fix cpu frequencies that for now are to hight
