### ISSUE TITLE
please fix camera after intel wifi

### ISSUE THREAD

**Issue by ske1996** [Edoardo001/Matebook-13-Hackintosh#14]
Thank for u guys did everything.my loptop(matebook13 2019ver. i7 512g mx250)i used ur efi file to hackintosh and i tried camera that donot work.but i realized it could be discerned by system.and i saw some camera dose work in matebook 14,but it just some of them,not all of them.so,i think the reason about camera not work is the different camera supplier of huawei.and just the camera which made by azurewave canot work.so i think get the kext (or find something in dsdt)of the non-made-by-azurewave's camera maybe  could be helpful.

**Comment by ske1996** [comment]
Additional:the kext or dsdt of camera which non-made-by-azuerwave in matebook14

**Comment by Edoardo001** [comment]
Join on telegram group to talk about it, link on guide page. Camera is correcly read by system but seems isn't compatible. I need people that test some fixes because in this horrible moment i am really busy with my work.
