### ISSUE TITLE
Battery Icon not working

### ISSUE THREAD

**Issue by skynightz93** [Edoardo001/Matebook-13-Hackintosh#17]
Hi Bro,

First, I want to say Thank You for this project. However, currenly i am having the issue with Battery Icon not working and i cannot know the battery information. However, if I boot from Drive that i use for installation, i can see the battery icon without any issue. May I know which Kext or file that i should take from usb drive to make it work? Thank you again.

**Comment by Edoardo001** [comment]
Fake Smc and fakesmc batttery

**Comment by skynightz93** [comment]
> Fake Smc and fakesmc batttery

Thank. Let me try to change it

**Comment by skynightz93** [comment]
Still not able to find where is FakeSMC, where should i take from bootable drive?

**Comment by skynightz93** [comment]
Nevermind. Found the fix for the issue. SMCBatteryManager is the culprit. Need to remove it and work for me. However, now i got another issue where my touchpad cannot work. It is not working once i change CPUfriend file. After revert, still got the issue. Need to find out while

**Comment by Edoardo001** [comment]
You have to rebuild kext cache
