### ISSUE TITLE
Sound fix - Jack

### ISSUE THREAD

**Issue by Pedroooow** [Edoardo001/Matebook-13-Hackintosh#19]
Hey !

Tried the fix provided in the latest updates for the jack output, didn't work for me and actually messed up some things: 

I had a prohibited bug on the boot, had to reboot from the usb install. 

Firstly, when patching property devices, I only see PciRoot(**0x0**)/Pci(0x1f,0x3) instead of PciRoot(**9x9**)/Pci(0x1f,0x3). 

Tried to change it, didn't work. 

Also, when trying to install the AlcPlugFixx anyway, I get a "cannot access allowlist" despite trying to change the permissions. 

Any idea ?

**Comment by Edoardo001** [comment]
Try replacing file you have messed with the one from the AfterInstall. Are you on Catalina?

**Comment by Pedroooow** [comment]
Hey, 
I tried again, got the same "cannot access allowlist" error message when openning autoinstal, but this time I updated Clover to the latest version. 

It works, so I guess that was an issue from Clover... anyways, that works perfect, so thank you ! 

I'm closing :)
