### ISSUE TITLE
a ac9560 kext ready

### ISSUE THREAD

**Issue by ske1996** [Edoardo001/Matebook-13-Hackintosh#22]
http://bbs.pcbeta.com/viewthread-1856465-1-2.html

what can that do?
1.save a list which some wifipot u always use
2.dont have to do anything,but make it in your desktop.
3.matebook 13 2019 i7 mx250 tested,works

how to use it?
1.make the intelwifi folder at ur desktop.
2.click run.command
3.press "a"
4. input ur ssid
5.input the password of that ssid,if it have to
6.done.

DO NOT copy AppleIntelWiFi.kext to L/E or clover folder,just make it in intelwifi folder at ur desktop.

I am not the developer,this kext from "林嘉杰" in pcbeta.com(http://bbs.pcbeta.com/viewthread-1856465-1-2.html)
the basic code is from  @zxystd 

download link:
https://www.icloud.com/iclouddrive/05e-GvtaLsrFAll8Px4qlFJDg#intelwifi

**Comment by Edoardo001** [comment]
Will post my translated version

**Comment by ske1996** [comment]
🤣🤣🤣but he always upgrade it atleast once a week
