### ISSUE TITLE
Dual-boot support

### ISSUE THREAD

**Issue by Balzac-Guan** [Edoardo001/Matebook-13-Hackintosh#26]
Thanks for all of you making OC boot loader available on matebook13 model :)  I want to know whether the dual-boot support is on your timeline? My Windows OS cannot boot from OC  :(

**Comment by Edoardo001** [comment]
Don't know maybe never. If you search on the web you will find some ways. Unfortunately my pare time it's not enough to do the things completely

**Comment by dolphinmax** [comment]
I booted into windowsPE and with  of the BSDboot program I registered(added in UEFI) two records from the folder efi / windows / boot / bootmgfv. efi and another record macos / efi/OC/opencore.efi and put this record first. My macos are loaded by default and through F12 I can load win 10

**Comment by Balzac-Guan** [comment]
> Don't know maybe never. If you search on the web you will find some ways. Unfortunately my pare time it's not enough to do the things completely

OK I would try it later. Thanks again :)
