### ISSUE TITLE
Voodoo times out, trackpad/touchscreen unresponsive

### ISSUE THREAD

**Issue by AyserJamshidi** [Edoardo001/Matebook-13-Hackintosh#27]
Model: WRT-W19. (i5, Intel gfx)
BIOS version is latest (PC Manager claims latest, BIOS screen claims v1.15 even though Huawei site claims v1.27 being latest.)

Everything else seems to work perfectly fine aside from the touchpad/touchscreen becoming unresponsive after some time (typically 5-15 minutes, but can go longer).  When this happens, if I let the computer idle long enough to sleep, if I close the clamshell and open it again and get it out of sleep, touchscreen and mouse work again, but only for, again, 5-15 minutes until this happens again.  

Things I've tried:
- Using all versions of OpenCorePost **after** fresh installs.
- Using the most up to date OpenCore, VirtualSMC, Lilu, WhateverGreen, VoodooI2C, VoodooI2CHID, VoodooPS2Controller.
- Using multiple SATA/NVMe SSDs (SATA SSDs via external hub) (Intel 530 SSD, Crucial MX 300 SSD, Some random SanDisk SSD / ADATA SX8200 pro NVMe).  They all install fine (with no touchpad working, have to use USB mouse).
- Disabled most ACPI/Kexts (except for the following: AWAC.aml, EC-USBX-LAPTOP.aml, XOSI.aml / Lilu.kext, Voodoo*.kext, VirtualSMC.kext, FacePCIID*.kext, WhateverGreen.kext)

All of this has been tested with a fresh MacOS Catalina 10.15.5 install each time while being installed using the left USB-C port.

> VoodooI2CControllerDriver::pci8086,9de9 Warning: Timeout waiting for bus not to be busy

dmesg is spammed with the message above once the touchpad/touchscreen become unresponsive.  I feel like this is a unique problem with my laptop as I don't see anyone else having a problem with this, but I don't understand why when I have the same setup as others have.

**Comment by Edoardo001** [comment]
Check bios settings... I've never had something similar, no one of the users. Come in telegram group, maybe someone has experienced same and know solution

**Comment by AyserJamshidi** [comment]
To anyone that wants a hacky workaround, you can see more information along with patched kexts for this workaround.
https://github.com/VoodooI2C/VoodooI2C/issues/319

This will allow the trackpad to stay working.  The cursor will randomly become invisible (usually when the touch screen hangs) and can easily be fixed by moving the invisible cursor all the way up to the Mac menu bar and just clicking.
