### ISSUE TITLE
Where is the info about the Wi-Fi kexts?

### ISSUE THREAD

**Issue by validatedev** [Edoardo001/Matebook-13-Hackintosh#4]
Cannot find any related information about Intel Wi-Fi kexts on the internet. Can you share please?

**Comment by Edoardo001** [comment]
The information are here and there on the web.
Here is a big part https://github.com/zxystd/AppleIntelWifiAdapter/issues/6 .
Unfortunately the guy has no GitHub, but we know he released in a private forum a test kext that works even with some workaround(ssid and password in the code of the kext) but it gets random panic every 20min.

But it's a enourmus  step, the hard part has done, now we have just to wait.

**Comment by validatedev** [comment]
Wow, nice info! Thanks!
